use_frameworks!

platform :ios, '12.0'

target 'forceUpdate_Example' do
  pod 'forceUpdate/ForceUpdate', :path => '../'


  pod 'AppsOnAirIOSCore', :git => 'https://github.com/harshil-gandhi-us/AppsOnAirIOSCore'


  target 'forceUpdate_Tests' do
    inherit! :search_paths
  end
end
