use_frameworks!
# source 'https://github.com/harshil-gandhi-us/AppsOnAirIOSCore.git'
# source 'https://github.com/CocoaPods/Specs.git' 
platform :ios, '12.0'

target 'forceUpdate_Example' do
  pod 'forceUpdate/ForceUpdate', :path => '../'

  pod 'AppsOnAirIOSCore', :git => 'https://github.com/harshil-gandhi-us/AppsOnAirIOSCore.git'


  target 'forceUpdate_Tests' do
    inherit! :search_paths
  end
end
